
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# إعادة توجيه SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# تحسين الأداء - ضغط الملفات
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# PWA headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

# متغيرات الإنتاج
[context.production.environment]
  VITE_SUPABASE_URL = "https://kdczoztkdnkvrofdloja.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkY3pvenRrZG5rdnJvZmRsb2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTkxMTEsImV4cCI6MjA2NTczNTExMX0.33cS8NJoILLFExLu6T3oCSbgnS7k177y4Csy9hdCfA0"
